version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
        POSTGRES_DB: 'ecommerce'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
